"""add document to ticket

Revision ID: 208dc73343b2
Revises: 9476ef11c835
Create Date: 2025-07-17 16:27:58.361992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '208dc73343b2'
down_revision = '9476ef11c835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('tanggal_catatan',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('tanggal_catatan',
               existing_type=sa.String(length=10),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
