"""add document to ticket

Revision ID: 74d9c6cbc994
Revises: 7d30fd2b68a5
Create Date: 2025-07-16 15:50:38.765913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d9c6cbc994'
down_revision = '7d30fd2b68a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('document')

    # ### end Alembic commands ###
