"""add status_case field

Revision ID: 9476ef11c835
Revises: 93c5ea577189
Create Date: 2025-07-17 16:21:12.702216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9476ef11c835'
down_revision = '93c5ea577189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catatan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tanggal_catatan', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('tanggal_catatan')
        batch_op.drop_column('catatan')

    # ### end Alembic commands ###
